In [1]:
import pandas as pd

kopoCD = pd.read_csv("./dataset/kopo_customerdata.csv")
kopoCD

kopoCD2 = kopoCD[["CUSTOMERCODE","STATENAME","GENDER","TOTAL_AMOUNT"]]
kopoCD2

kopoCDcolumns=kopoCD.columns

a = kopoCDcolumns.get_loc("STATENAME")
a

kopoCD3 = kopoCD.iloc[0:6,[a]]
kopoCD3

kopoCSN = pd.read_csv("./dataset/kopo_channel_seasonality_new.csv")
kopoCSN

import numpy as np

kopoCSN["QTY_NEW"] = np.where(kopoCSN["QTY"]<0,0,kopoCSN["QTY"])
kopoCSN

kopoCSN["YEARWEEK"] = kopoCSN["YEARWEEK"].astype(str)

kopoCSN["YEAR"] = kopoCSN["YEARWEEK"].str[0:4]
kopoCSN["WEEK"] = kopoCSN["YEARWEEK"].str[4:]
kopoCSN

kopoCSN["WEEK"] = kopoCSN["WEEK"].astype(int)

refinedSelloutData = kopoCSN[kopoCSN.WEEK < 53]
refinedSelloutData

sortedData = refinedSelloutData.sort_values(["REGIONID","PRODUCT","YEARWEEK"],ascending=[True,False,True])
sortedData

groupData = sortedData.\
groupby(["REGIONID","PRODUCT","YEAR"]).agg\
(['mean','std'])['QTY_NEW']
groupData

groupData2 = groupData.reset_index()
groupData2

groupData2.columns = ["REGIONID","PRODUCT","YEAR","QTY_MEAN","QTY_STD"]
groupData2

     REGIONID    PRODUCT  YEAR       QTY_MEAN        QTY_STD
0         A00  PRODUCT34  2014     275.961538     162.179634
1         A00  PRODUCT34  2015      86.634615      73.246034
2         A00  PRODUCT34  2016      36.576923      94.897539
3         A00  PRODUCT58  2014       2.673077       3.889257
4         A00  PRODUCT58  2015       5.711538       6.675494
5         A00  PRODUCT58  2016     307.365385     407.622857
6         A00  PRODUCT59  2014   27418.692308   11461.345740
7         A00  PRODUCT59  2015   52240.846154    8303.813637
8         A00  PRODUCT59  2016   28213.173077    9583.361555
9         A01   PRODUCT1  2014    8622.461538    3142.837761
10        A01   PRODUCT1  2015    6384.788462    2561.668125
11        A01   PRODUCT1  2016    2131.076923    1835.068015
12        A01  PRODUCT12  2014  169397.826923  176743.049878
13        A01  PRODUCT12  2015  195479.884615  194774.813335
14        A01  PRODUCT12  2016  225598.500000  223957.833468
15        A01  PRODUCT14  2014   12495.769231    6870.540503
16        A01  PRODUCT14  2015   18622.923077    8993.732290
17        A01  PRODUCT14  2016   22567.307692    9437.701749
18        A01  PRODUCT15  2014    5076.769231    1732.873242
19        A01  PRODUCT15  2015    4830.211538    1560.567171
20        A01  PRODUCT15  2016    4359.192308    1194.369914
21        A01  PRODUCT16  2014    1208.192308     481.798837
22        A01  PRODUCT16  2015    1450.826923     910.749997
23        A01  PRODUCT16  2016    1524.538462     727.927530
24        A01  PRODUCT19  2014    2588.711538     830.249651
25        A01  PRODUCT19  2015    3582.730769     876.973117
26        A01  PRODUCT19  2016    3845.884615     819.779182
27        A01   PRODUCT2  2014     376.961538     198.635439
28        A01   PRODUCT2  2015   19318.096154   13524.218669
29        A01   PRODUCT2  2016   48481.326923   16741.522764
...       ...        ...   ...            ...            ...
2352      A68  PRODUCT58  2014       2.942308       4.980013
2353      A68  PRODUCT58  2015       0.692308       0.875337
2354      A68  PRODUCT58  2016       1.346154       5.190053
2355      A68  PRODUCT59  2014    5558.750000    3556.830798
2356      A68  PRODUCT59  2015   11542.365385    6722.363351
2357      A68  PRODUCT59  2016    6239.403846    3931.333926
2358      A69  PRODUCT34  2014     234.307692     327.175227
2359      A69  PRODUCT34  2015      88.076923      40.826196
2360      A69  PRODUCT34  2016     177.326923      80.456716
2361      A69  PRODUCT58  2014       1.192308       1.547147
2362      A69  PRODUCT58  2015       3.961538       4.356476
2363      A69  PRODUCT58  2016       8.365385       7.340537
2364      A69  PRODUCT59  2014    1570.730769    1288.559054
2365      A69  PRODUCT59  2015    9655.673077    4826.066594
2366      A69  PRODUCT59  2016   13596.500000    3262.771134
2367      A70  PRODUCT34  2014    1455.269231     914.891960
2368      A70  PRODUCT34  2015    2764.115385    1555.432487
2369      A70  PRODUCT34  2016    2280.615385    1595.475320
2370      A70  PRODUCT58  2014      14.384615      15.682079
2371      A70  PRODUCT58  2015      38.038462      43.204013
2372      A70  PRODUCT58  2016     129.769231      62.637962
2373      A70  PRODUCT59  2014   27002.326923   21271.358758
2374      A70  PRODUCT59  2015   78249.230769   12604.726679
2375      A70  PRODUCT59  2016  102784.307692   16613.683300
2376      A77   PRODUCT1  2014    2262.653846     914.206071
2377      A77   PRODUCT1  2015    3030.019231     846.496783
2378      A77   PRODUCT1  2016    3375.326923     702.359238
2379      A77  PRODUCT12  2014    2035.788462     762.881491
2380      A77  PRODUCT12  2015    3540.980769     852.593402
2381      A77  PRODUCT12  2016    4837.153846    1841.810824

[2382 rows x 5 columns]

In [2]:
sortedData = refinedSelloutData.sort_values(["REGIONID","PRODUCT","YEARWEEK"],ascending=[True,False,True])
sortedData

       REGIONID    PRODUCT YEARWEEK      QTY  QTY_NEW  YEAR  WEEK
297         A00  PRODUCT59   201401   9988.0   9988.0  2014     1
1756        A00  PRODUCT59   201402   9005.0   9005.0  2014     2
3124        A00  PRODUCT59   201403   8416.0   8416.0  2014     3
204         A00  PRODUCT59   201404   8553.0   8553.0  2014     4
4368        A00  PRODUCT59   201405  10355.0  10355.0  2014     5
4312        A00  PRODUCT59   201406  13799.0  13799.0  2014     6
6287        A00  PRODUCT59   201407  17292.0  17292.0  2014     7
6402        A00  PRODUCT59   201408  16369.0  16369.0  2014     8
5157        A00  PRODUCT59   201409  15047.0  15047.0  2014     9
7436        A00  PRODUCT59   201410  15895.0  15895.0  2014    10
10122       A00  PRODUCT59   201411  16255.0  16255.0  2014    11
8843        A00  PRODUCT59   201412  17339.0  17339.0  2014    12
10812       A00  PRODUCT59   201413  17419.0  17419.0  2014    13
11273       A00  PRODUCT59   201414  22482.0  22482.0  2014    14
12127       A00  PRODUCT59   201415  22007.0  22007.0  2014    15
13436       A00  PRODUCT59   201416  19690.0  19690.0  2014    16
13638       A00  PRODUCT59   201417  17791.0  17791.0  2014    17
14443       A00  PRODUCT59   201418  16455.0  16455.0  2014    18
15827       A00  PRODUCT59   201419  17133.0  17133.0  2014    19
15457       A00  PRODUCT59   201420  18901.0  18901.0  2014    20
17078       A00  PRODUCT59   201421  21135.0  21135.0  2014    21
16965       A00  PRODUCT59   201422  22455.0  22455.0  2014    22
17837       A00  PRODUCT59   201423  25364.0  25364.0  2014    23
19464       A00  PRODUCT59   201424  25368.0  25368.0  2014    24
49426       A00  PRODUCT59   201425  23751.0  23751.0  2014    25
22467       A00  PRODUCT59   201426  25772.0  25772.0  2014    26
49144       A00  PRODUCT59   201427  25533.0  25533.0  2014    27
26939       A00  PRODUCT59   201428  26506.0  26506.0  2014    28
27838       A00  PRODUCT59   201429  26775.0  26775.0  2014    29
47551       A00  PRODUCT59   201430  32364.0  32364.0  2014    30
...         ...        ...      ...      ...      ...   ...   ...
74308       A77   PRODUCT1   201623   3289.0   3289.0  2016    23
65353       A77   PRODUCT1   201624   2866.0   2866.0  2016    24
60504       A77   PRODUCT1   201625   2739.0   2739.0  2016    25
101445      A77   PRODUCT1   201626   2555.0   2555.0  2016    26
124471      A77   PRODUCT1   201627   2713.0   2713.0  2016    27
103774      A77   PRODUCT1   201628   2615.0   2615.0  2016    28
91997       A77   PRODUCT1   201629   3436.0   3436.0  2016    29
122121      A77   PRODUCT1   201630   2918.0   2918.0  2016    30
96745       A77   PRODUCT1   201631   3092.0   3092.0  2016    31
101639      A77   PRODUCT1   201632   5040.0   5040.0  2016    32
101441      A77   PRODUCT1   201633   3980.0   3980.0  2016    33
124467      A77   PRODUCT1   201634   3489.0   3489.0  2016    34
122701      A77   PRODUCT1   201635   2764.0   2764.0  2016    35
108821      A77   PRODUCT1   201636   3151.0   3151.0  2016    36
111701      A77   PRODUCT1   201637   1995.0   1995.0  2016    37
118387      A77   PRODUCT1   201638   4699.0   4699.0  2016    38
113558      A77   PRODUCT1   201639   3665.0   3665.0  2016    39
118524      A77   PRODUCT1   201640   3021.0   3021.0  2016    40
117574      A77   PRODUCT1   201641   3299.0   3299.0  2016    41
121417      A77   PRODUCT1   201642   3048.0   3048.0  2016    42
92762       A77   PRODUCT1   201643   3790.0   3790.0  2016    43
108565      A77   PRODUCT1   201644   2450.0   2450.0  2016    44
99444       A77   PRODUCT1   201645   2925.0   2925.0  2016    45
99557       A77   PRODUCT1   201646   2998.0   2998.0  2016    46
103154      A77   PRODUCT1   201647   2920.0   2920.0  2016    47
102293      A77   PRODUCT1   201648   3070.0   3070.0  2016    48
97526       A77   PRODUCT1   201649   4222.0   4222.0  2016    49
102330      A77   PRODUCT1   201650   4422.0   4422.0  2016    50
101212      A77   PRODUCT1   201651   3671.0   3671.0  2016    51
92326       A77   PRODUCT1   201652   2759.0   2759.0  2016    52

[123864 rows x 7 columns]