In [1]:
import pandas as pd

In [ ]:
# 데이터 불러오기

In [2]:
actualData = pd.read_csv("./dataset/pro_actual_sales.csv")

In [3]:
actualData

,regionSeg1,productSeg1,productSeg2,regionSeg2,regionSeg3,productSeg3,yearweek,year,week,qty
0,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201306,2013,6,5
1,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201307,2013,7,8
2,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201308,2013,8,7
3,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201309,2013,9,1
4,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201310,2013,10,1
5,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201311,2013,11,1
6,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201312,2013,12,1
7,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201313,2013,13,2
8,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201314,2013,14,1
9,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201315,2013,15,6
10,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201316,2013,16,5
11,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201317,2013,17,2
12,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201318,2013,18,1
13,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201319,2013,19,3
14,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201320,2013,20,2
15,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201321,2013,21,6
16,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201322,2013,22,2
17,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201323,2013,23,5
18,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201324,2013,24,3
19,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201325,2013,25,1
20,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201326,2013,26,1
21,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201327,2013,27,3
22,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201328,2013,28,1
23,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201330,2013,30,1
24,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201332,2013,32,3
25,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201333,2013,33,4
26,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201334,2013,34,1
27,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201335,2013,35,2
28,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201336,2013,36,4
29,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0445,201338,2013,38,1
...,...,...,...,...,...,...,...,...,...,...
140837,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201616,2016,16,13
140838,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201617,2016,17,18
140839,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201618,2016,18,5
140840,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201619,2016,19,27
140841,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201620,2016,20,12
140842,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201621,2016,21,35
140843,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201622,2016,22,30
140844,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201623,2016,23,15
140845,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201624,2016,24,4
140846,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201625,2016,25,47
140847,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201626,2016,26,89
140848,A01,NaN,PG05,SALESID0001,SITEID0001,ITEM0033,201627,2016,27,59
140849,A01,NaN,PG05,SALESID0001,SITEID0007,ITEM0034,201608,2016,8,1
140850,A01,NaN,PG05,SALESID0001,SITEID0006,ITEM0034,201601,2016,1,1
140851,A01,NaN,PG05,SALESID0001,SITEID0006,ITEM0034,201602,2016,2,1
140852,A01,NaN,PG05,SALESID0001,SITEID0006,ITEM0034,201604,2016,4,1
140853,A01,NaN,PG05,SALESID0001,SITEID0006,ITEM0034,201608,2016,8,1
140854,A01,NaN,PG05,SALESID0001,SITEID0006,ITEM0034,201609,2016,9,1
140855,A01,NaN,PG05,SALESID0001,SITEID0005,ITEM0034,201601,2016,1,5
140856,A01,NaN,PG05,SALESID0001,SITEID0005,ITEM0034,201602,2016,2,1
140857,A01,NaN,PG05,SALESID0001,SITEID0005,ITEM0034,201603,2016,3,2
140858,A01,NaN,PG05,SALESID0001,SITEID0005,ITEM0034,201604,2016,4,2
140859,A01,NaN,PG05,SALESID0001,SITEID0005,ITEM0034,201606,2016,6,1
140860,A01,NaN,PG05,SALESID0001,SITEID0005,ITEM0034,201607,2016,7,3
140861,A01,NaN,PG05,SALESID0001,SITEID0005,ITEM0034,201610,2016,10,1
140862,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0034,201601,2016,1,13
140863,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0034,201602,2016,2,4
140864,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0034,201607,2016,7,6
140865,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0034,201608,2016,8,1
140866,A01,NaN,PG05,SALESID0001,SITEID0004,ITEM0034,201609,2016,9,8

In [4]:
# 예외처리

In [6]:
# postWeek 함수 만들기( 연도주차를 계산하는 함수)

In [7]:
def postWeek(inputYW, gapW):
    
    inputYearWeek = str(inputYW) # 타입을 str로 바꿔주는 부분(Year와 Week로 나눠주기 위해)
    intputYear = inputYearWeek[0:4] ## Year 부분을 만드는 부분
    intputWeek = inputYearWeek[4: ] ## Week 부분을 만드는 부분
    
    inputGapW = int(gapW) ## 입력할 주차의 타입을 int로 바꿔주는 부분
    
    sumValue = int(inputWeek) + inputGapW ## inputWeek의 타입을 int로 바꿔주고 주차의 합을 구하는 부분
    
    lastWeek = week.last_week_of_year(curryear).week ## 마지막 주차를 나타내는 부분
    
    curryear = int(inputYear)
    
    while(sumValue> lastWeek):
        curryear += 1 ## 다음 연도로 넘어가는 부분
        sumValue = sumValue=lastWeek ## gap 주차와 합산되 총 주차
        lastWeek = week.last_week_of_year(curryear).week
    
    ##연도와 주차의 타입을 str로 바꿔서 lastanser(연도주차)를 만드는 부분
    if(sumValue>10):   
        lastanswer = str(curryear) + "0" + str(sumValue) ##주차가 10보다 작으면 앞에 0을 붙여주는 부분
    else:
        lastanswer = str(curryear) + str(sumValue)
    return lasranswer

In [5]:
#비워져있는 주차 채우는 함수 만들기

In [ ]:
def minmaxweek(inputdf):
    inputdf.reset_index(drop = True, inplace = True)## 필요 없???
    minweek = min(inputdf['yearweek']) ## inputdf의 yearweek컬럼에 최솟값을 담은 부분
    maxweek = max(inputdf['yearweek']) ## inputdf의 yearweek컬럼에 최댓값을 담은 부분
    
    fullyearweek = [] ## 빈 배열을 만들어서 minweek부터 maxweek까지의 모든 yearweek를
                      ## 담아주려는 부분
    i = minweek ## 처음 시작부분을 최소 yearweek로 시작하기 위해서 나타낸 부분
    fullyearweek.append(i) ## 최소 주차를 추가하는 부분
    
    ## 모든 주차를 생성해서 fullyearweek에 담으려는 부분
    while (max(fullyearweek) < maxweek):
        inputWeek = int(postweek(str(max(fullyearweek)),1)) ##입력할 주차는 최대 주차 다음의 주차
        fullyearweek.append(inputWeek) ## fullyearweek에 담어주는 부분
    ## fullyearweek와 inputdf.yearweek.values의 차집합을 구하는 부분    
    newyearweekList = list(set(fullyearweek).difference(set(list(inputdf.yearweek.values))))
    
    ## newyearweekList의 길이 만큼 반복하여 inputdf에 비워진 주차를 추가하는 부분
    for i in range(len(newyearweekList)):
        inputdf.loc[len(inputdf)] = list(inputdf.loc[0].values) ## 첫번째 행을 가지고 복사함
                                                                ## 어느 행이든 상관없음
        inputdf.loc[len(inputdf)-1,'yearweek'] = newyearweekList[i] ## 컬럼yearweek의 i번째를 추가  
        inputdf.loc[len(inputdf)-1,'year'] = round(newyearweekList[i]/100) ## 컬럼year의 i번째를 추가  
        inputdf.loc[len(inputdf)-1,'week'] = newyearweekList[i]%100 ## 컬럼week의 i번째를 추가  
        inputdf.loc[len(inputdf)-1,'qty'] = 0 # 컬럼 값 변경
                           
    inputdf.sort_values('yearweek') ## yearweek컬럼을 정렬
    inputdf.reset_index(drop = True, inplace = True) ## index를 다시 해주는 부분
    return inputdf

In [ ]:
## 그룹바이 하기

In [ ]:
groupkey1 = ['regionSeg1']